version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - godox
    - gomodguard # deprecated
    - musttag
    - nlreturn
    - paralleltest
    - testpackage
    - wsl # deprecated
  settings:
    cyclop:
      max-complexity: 15
    gosec:
      excludes:
        - G115 # causes too many false positives with VM ids that can never be negative
    lll:
      line-length: 200
      tab-width: 2
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      ignore-names:
        - vm
        - wg
        - ig
    wsl_v5:
      disable:
        - range
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*_test.go$"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
